name: Pages

on:
  push:
    branches:
      - master # default branch
  release:
    types:
      - published

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: 安装 Hexo
        run: |
          export TZ='Asia/Shanghai'
          npm install hexo-cli -g

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      - name: Install Dependencies
        run: |
          npm install --save
      #          npm install gulp-cli -g #全局安装gulp

      - name: 生成静态文件
        run: |
          hexo clean
          hexo g
#          gulp

      - name: 部署到GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages  # 部署到gh-pages分支
          folder: public  # Hexo生成的静态文件目录
          commit-message: "${{ github.event.head_commit.message }} Updated By Github Actions"
